In [2]:
import matplotlib
import numpy as np

In [5]:
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((2,1))

In [11]:
A+B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [13]:
C = np.ones((2,1))
A+C

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [14]:
W = np.random.randint(0, 10, [4,1])
Z = np.ones((1,3))

W+Z

array([[4., 4., 4.],
       [6., 6., 6.],
       [3., 3., 3.],
       [5., 5., 5.]])